name: Build 32-bit Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-32bit:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 32-bit
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x86'  # Força 32 bits
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyodbc requests schedule pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole paradox_monitor.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: paradox-monitor-32bit
        path: dist/paradox_monitor.exe
